# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dn <- function(x, mu, sd) {
    .Call('_rcpm_dn', PACKAGE = 'rcpm', x, mu, sd)
}

dmvnrmarma <- function(x, mean, sigma, logd = FALSE) {
    .Call('_rcpm_dmvnrmarma', PACKAGE = 'rcpm', x, mean, sigma, logd)
}

mspline2 <- function(x, tmin, tmax, tint, k, intercept) {
    .Call('_rcpm_mspline2', PACKAGE = 'rcpm', x, tmin, tmax, tint, k, intercept)
}

ispline2 <- function(x, tmin, tmax, tint, k, intercept) {
    .Call('_rcpm_ispline2', PACKAGE = 'rcpm', x, tmin, tmax, tint, k, intercept)
}

mspline <- function(x, tmin, tmax, tint) {
    .Call('_rcpm_mspline', PACKAGE = 'rcpm', x, tmin, tmax, tint)
}

ispline <- function(x, tmin, tmax, tint) {
    .Call('_rcpm_ispline', PACKAGE = 'rcpm', x, tmin, tmax, tint)
}

dmvnrmarma1d <- function(x, mean, sigma, logd = FALSE) {
    .Call('_rcpm_dmvnrmarma1d', PACKAGE = 'rcpm', x, mean, sigma, logd)
}

ScoreInd <- function(data, Beta0, Beta1, sigma, mutau, sigmatau, B, MATmus, nbnodes, nd, newnodes, newweights, scorevar, timevar, groupvar) {
    .Call('_rcpm_ScoreInd', PACKAGE = 'rcpm', data, Beta0, Beta1, sigma, mutau, sigmatau, B, MATmus, nbnodes, nd, newnodes, newweights, scorevar, timevar, groupvar)
}

transfY <- function(Y, link, param, objtransi) {
    .Call('_rcpm_transfY', PACKAGE = 'rcpm', Y, link, param, objtransi)
}

lvsblNCgen <- function(param, data, nq, grp, weights, nodes, scorevar, timevar, covariate, REadjust, model, link, objtrans, gamma, loglik) {
    .Call('_rcpm_lvsblNCgen', PACKAGE = 'rcpm', param, data, nq, grp, weights, nodes, scorevar, timevar, covariate, REadjust, model, link, objtrans, gamma, loglik)
}

lvsbllin <- function(param, data, grp, scorevar, timevar, link, objtrans, loglik) {
    .Call('_rcpm_lvsbllin', PACKAGE = 'rcpm', param, data, grp, scorevar, timevar, link, objtrans, loglik)
}

bilvsblNC <- function(param, data, nq, adapt, grp, weights, nodes, newnodes, newweights, scorevar1, scorevar2, timevar, covariate, REadjust, model, link1, link2, objtrans1, objtrans2, gamma) {
    .Call('_rcpm_bilvsblNC', PACKAGE = 'rcpm', param, data, nq, adapt, grp, weights, nodes, newnodes, newweights, scorevar1, scorevar2, timevar, covariate, REadjust, model, link1, link2, objtrans1, objtrans2, gamma)
}

IndRePostDis <- function(re, data, rcpmeObj, scorevar, timevar, model, statutvar, gamma, link) {
    .Call('_rcpm_IndRePostDis', PACKAGE = 'rcpm', re, data, rcpmeObj, scorevar, timevar, model, statutvar, gamma, link)
}

IndRePostDis2 <- function(re, data, rcpmeObj, scorevar, timevar, model, gamma, link) {
    .Call('_rcpm_IndRePostDis2', PACKAGE = 'rcpm', re, data, rcpmeObj, scorevar, timevar, model, gamma, link)
}

BivIndRePostDis <- function(re, data, rcpmeObj, scorevar1, scorevar2, timevar, model, gamma, link1, link2) {
    .Call('_rcpm_BivIndRePostDis', PACKAGE = 'rcpm', re, data, rcpmeObj, scorevar1, scorevar2, timevar, model, gamma, link1, link2)
}

BivIndRePostDis2 <- function(re, data, rcpmeObj, scorevar1, scorevar2, timevar, model, gamma, link1, link2) {
    .Call('_rcpm_BivIndRePostDis2', PACKAGE = 'rcpm', re, data, rcpmeObj, scorevar1, scorevar2, timevar, model, gamma, link1, link2)
}

