# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('_rcpm_rcpparma_hello_world', PACKAGE = 'rcpm')
}

rcpparma_outerproduct <- function(x) {
    .Call('_rcpm_rcpparma_outerproduct', PACKAGE = 'rcpm', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_rcpm_rcpparma_innerproduct', PACKAGE = 'rcpm', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_rcpm_rcpparma_bothproducts', PACKAGE = 'rcpm', x)
}

dn <- function(x, mu, sd) {
    .Call('_rcpm_dn', PACKAGE = 'rcpm', x, mu, sd)
}

dmvnrmarma <- function(x, mean, sigma, logd = FALSE) {
    .Call('_rcpm_dmvnrmarma', PACKAGE = 'rcpm', x, mean, sigma, logd)
}

dmvnrmarma1d <- function(x, mean, sigma, logd = FALSE) {
    .Call('_rcpm_dmvnrmarma1d', PACKAGE = 'rcpm', x, mean, sigma, logd)
}

ScoreInd <- function(data, Beta0, Beta1, sigma, mutau, sigmatau, B, MATmus, nbnodes, nd, newnodes, newweights, scorevar, timevar, groupvar) {
    .Call('_rcpm_ScoreInd', PACKAGE = 'rcpm', data, Beta0, Beta1, sigma, mutau, sigmatau, B, MATmus, nbnodes, nd, newnodes, newweights, scorevar, timevar, groupvar)
}

lvsblNCgen <- function(param, data, nq, grp, weights, nodes, scorevar, timevar, covariate, REadjust) {
    .Call('_rcpm_lvsblNCgen', PACKAGE = 'rcpm', param, data, nq, grp, weights, nodes, scorevar, timevar, covariate, REadjust)
}

bilvsblNC <- function(param, data, nq, adapt, grp, weights, nodes, newnodes, newweights, scorevar1, scorevar2, timevar, covariate, REadjust) {
    .Call('_rcpm_bilvsblNC', PACKAGE = 'rcpm', param, data, nq, adapt, grp, weights, nodes, newnodes, newweights, scorevar1, scorevar2, timevar, covariate, REadjust)
}

