# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dn <- function(x, mu, sd) {
    .Call('_rcpm_dn', PACKAGE = 'rcpm', x, mu, sd)
}

dmvnrmarma <- function(x, mean, sigma, logd = FALSE) {
    .Call('_rcpm_dmvnrmarma', PACKAGE = 'rcpm', x, mean, sigma, logd)
}

mspline2 <- function(x, tmin, tmax, tint, k, intercept) {
    .Call('_rcpm_mspline2', PACKAGE = 'rcpm', x, tmin, tmax, tint, k, intercept)
}

ispline2 <- function(x, tmin, tmax, tint, k, intercept) {
    .Call('_rcpm_ispline2', PACKAGE = 'rcpm', x, tmin, tmax, tint, k, intercept)
}

mspline <- function(x, tmin, tmax, tint) {
    .Call('_rcpm_mspline', PACKAGE = 'rcpm', x, tmin, tmax, tint)
}

ispline <- function(x, tmin, tmax, tint) {
    .Call('_rcpm_ispline', PACKAGE = 'rcpm', x, tmin, tmax, tint)
}

dmvnrmarma1d <- function(x, mean, sigma, logd = FALSE) {
    .Call('_rcpm_dmvnrmarma1d', PACKAGE = 'rcpm', x, mean, sigma, logd)
}

ScoreInd <- function(data, Beta0, Beta1, sigma, mutau, sigmatau, B, MATmus, nbnodes, nd, newnodes, newweights, scorevar, timevar, groupvar) {
    .Call('_rcpm_ScoreInd', PACKAGE = 'rcpm', data, Beta0, Beta1, sigma, mutau, sigmatau, B, MATmus, nbnodes, nd, newnodes, newweights, scorevar, timevar, groupvar)
}

transfY <- function(Y, link, param, objtransi) {
    .Call('_rcpm_transfY', PACKAGE = 'rcpm', Y, link, param, objtransi)
}

lvsblNCgen <- function(param, data, nq, grp, weights, nodes, scorevar, timevar, covariate, age_of_diagnosis, REadjust, model, link, objtrans, gamma, loglik, two_means, intercept) {
    .Call('_rcpm_lvsblNCgen', PACKAGE = 'rcpm', param, data, nq, grp, weights, nodes, scorevar, timevar, covariate, age_of_diagnosis, REadjust, model, link, objtrans, gamma, loglik, two_means, intercept)
}

lvsbllin <- function(param, data, grp, scorevar, timevar, link, objtrans, loglik, intercept, covariate) {
    .Call('_rcpm_lvsbllin', PACKAGE = 'rcpm', param, data, grp, scorevar, timevar, link, objtrans, loglik, intercept, covariate)
}

bilvsblNC <- function(param, data, nq, adapt, grp, weights, nodes, newnodes, newweights, scorevar1, scorevar2, timevar, covariate, REadjust, model, link1, link2, objtrans1, objtrans2, gamma) {
    .Call('_rcpm_bilvsblNC', PACKAGE = 'rcpm', param, data, nq, adapt, grp, weights, nodes, newnodes, newweights, scorevar1, scorevar2, timevar, covariate, REadjust, model, link1, link2, objtrans1, objtrans2, gamma)
}

IndRePostDis <- function(re, data, rcpmeObj, scorevar, timevar, model, statutvar, gamma, link) {
    .Call('_rcpm_IndRePostDis', PACKAGE = 'rcpm', re, data, rcpmeObj, scorevar, timevar, model, statutvar, gamma, link)
}

IndRePostDis2 <- function(re, data, rcpmeObj, scorevar, timevar, model, gamma, link) {
    .Call('_rcpm_IndRePostDis2', PACKAGE = 'rcpm', re, data, rcpmeObj, scorevar, timevar, model, gamma, link)
}

BivIndRePostDis <- function(re, data, rcpmeObj, scorevar1, scorevar2, timevar, model, gamma, link1, link2) {
    .Call('_rcpm_BivIndRePostDis', PACKAGE = 'rcpm', re, data, rcpmeObj, scorevar1, scorevar2, timevar, model, gamma, link1, link2)
}

BivIndRePostDis2 <- function(re, data, rcpmeObj, scorevar1, scorevar2, timevar, model, gamma, link1, link2) {
    .Call('_rcpm_BivIndRePostDis2', PACKAGE = 'rcpm', re, data, rcpmeObj, scorevar1, scorevar2, timevar, model, gamma, link1, link2)
}

jacobi_eigenvalue <- function(n, A, it_max) {
    .Call('_rcpm_jacobi_eigenvalue', PACKAGE = 'rcpm', n, A, it_max)
}

moment_method <- function(n, moment) {
    .Call('_rcpm_moment_method', PACKAGE = 'rcpm', n, moment)
}

moments_normal <- function(m, mu, sigma) {
    .Call('_rcpm_moments_normal', PACKAGE = 'rcpm', m, mu, sigma)
}

moments_truncated_normal_ab <- function(m, mu, sigma, a, b) {
    .Call('_rcpm_moments_truncated_normal_ab', PACKAGE = 'rcpm', m, mu, sigma, a, b)
}

moments_truncated_normal_a <- function(m, mu, sigma, a) {
    .Call('_rcpm_moments_truncated_normal_a', PACKAGE = 'rcpm', m, mu, sigma, a)
}

moments_truncated_normal_b <- function(m, mu, sigma, b) {
    .Call('_rcpm_moments_truncated_normal_b', PACKAGE = 'rcpm', m, mu, sigma, b)
}

r8_huge <- function() {
    .Call('_rcpm_r8_huge', PACKAGE = 'rcpm')
}

r8_mop <- function(i) {
    .Call('_rcpm_r8_mop', PACKAGE = 'rcpm', i)
}

r8mat_cholesky_factor_upper <- function(n, a) {
    .Call('_rcpm_r8mat_cholesky_factor_upper', PACKAGE = 'rcpm', n, a)
}

r8mat_copy_new <- function(m, n, a1) {
    .Call('_rcpm_r8mat_copy_new', PACKAGE = 'rcpm', m, n, a1)
}

r8mat_diag_get_vector <- function(n, a) {
    .Call('_rcpm_r8mat_diag_get_vector', PACKAGE = 'rcpm', n, a)
}

r8mat_identity <- function(n) {
    .Call('_rcpm_r8mat_identity', PACKAGE = 'rcpm', n)
}

truncated_normal_ab_moment <- function(order, mu, s, a, b) {
    .Call('_rcpm_truncated_normal_ab_moment', PACKAGE = 'rcpm', order, mu, s, a, b)
}

truncated_normal_a_moment <- function(order, mu, sigma, a) {
    .Call('_rcpm_truncated_normal_a_moment', PACKAGE = 'rcpm', order, mu, sigma, a)
}

truncated_normal_b_moment <- function(order, mu, sigma, b) {
    .Call('_rcpm_truncated_normal_b_moment', PACKAGE = 'rcpm', order, mu, sigma, b)
}

